export type EquipmentCategory =
  | 'Cardio'
  | 'Strength'
  | 'Free Weights'
  | 'Functional'
  | 'Stretching'
  | 'Group Fitness';

export type EquipmentStatus =
  | 'Operational'
  | 'Maintenance Required'
  | 'Under Repair'
  | 'Out of Service';

export type MaintenancePriority = 'Low' | 'Medium' | 'High' | 'Critical';

export interface Equipment {
  id: string;
  name: string;
  category: EquipmentCategory;
  manufacturer: string;
  model: string;
  serialNumber: string;
  purchaseDate: string;
  warrantyExpiry: string;
  status: EquipmentStatus;
  location: string;
  lastMaintenance: string;
  nextMaintenance: string;
  maintenancePriority: MaintenancePriority;
  usageHours?: number;
  notes?: string;
}

export const equipment: Equipment[] = [
  {
    id: 'eq-1',
    name: 'Treadmill Pro X1',
    category: 'Cardio',
    manufacturer: 'Life Fitness',
    model: 'T5 Track',
    serialNumber: 'LF-TR-2023-001',
    purchaseDate: '2023-01-15',
    warrantyExpiry: '2026-01-15',
    status: 'Operational',
    location: 'Cardio Zone A',
    lastMaintenance: '2024-10-15',
    nextMaintenance: '2025-01-15',
    maintenancePriority: 'Low',
    usageHours: 2450,
  },
  {
    id: 'eq-2',
    name: 'Rowing Machine Elite',
    category: 'Cardio',
    manufacturer: 'Concept2',
    model: 'Model D',
    serialNumber: 'C2-ROW-2023-005',
    purchaseDate: '2023-02-20',
    warrantyExpiry: '2026-02-20',
    status: 'Operational',
    location: 'Cardio Zone B',
    lastMaintenance: '2024-11-01',
    nextMaintenance: '2025-02-01',
    maintenancePriority: 'Low',
    usageHours: 1820,
  },
  {
    id: 'eq-3',
    name: 'Smith Machine',
    category: 'Strength',
    manufacturer: 'Hammer Strength',
    model: 'HS-SM-500',
    serialNumber: 'HS-2022-098',
    purchaseDate: '2022-06-10',
    warrantyExpiry: '2027-06-10',
    status: 'Maintenance Required',
    location: 'Free Weights Area',
    lastMaintenance: '2024-08-10',
    nextMaintenance: '2024-11-20',
    maintenancePriority: 'High',
    notes: 'Bar needs lubrication, slight grinding noise',
  },
  {
    id: 'eq-4',
    name: 'Leg Press Machine',
    category: 'Strength',
    manufacturer: 'Cybex',
    model: 'VR3 Leg Press',
    serialNumber: 'CYB-LP-2023-012',
    purchaseDate: '2023-03-05',
    warrantyExpiry: '2026-03-05',
    status: 'Operational',
    location: 'Strength Training Zone',
    lastMaintenance: '2024-10-20',
    nextMaintenance: '2025-01-20',
    maintenancePriority: 'Low',
    usageHours: 1650,
  },
  {
    id: 'eq-5',
    name: 'Cable Crossover',
    category: 'Strength',
    manufacturer: 'Technogym',
    model: 'Selection 700',
    serialNumber: 'TG-CC-2022-034',
    purchaseDate: '2022-09-15',
    warrantyExpiry: '2027-09-15',
    status: 'Under Repair',
    location: 'Functional Training',
    lastMaintenance: '2024-09-15',
    nextMaintenance: '2024-12-15',
    maintenancePriority: 'Critical',
    notes: 'Cable snapped - replacement ordered',
  },
  {
    id: 'eq-6',
    name: 'Olympic Barbell Set',
    category: 'Free Weights',
    manufacturer: 'Rogue Fitness',
    model: 'Ohio Bar',
    serialNumber: 'RF-OB-2023-156',
    purchaseDate: '2023-01-20',
    warrantyExpiry: '2025-01-20',
    status: 'Operational',
    location: 'Free Weights Area',
    lastMaintenance: '2024-11-05',
    nextMaintenance: '2025-02-05',
    maintenancePriority: 'Low',
  },
  {
    id: 'eq-7',
    name: 'Assault Bike',
    category: 'Cardio',
    manufacturer: 'Assault Fitness',
    model: 'AssaultBike Pro',
    serialNumber: 'AF-AB-2023-078',
    purchaseDate: '2023-04-10',
    warrantyExpiry: '2026-04-10',
    status: 'Operational',
    location: 'CrossFit Area',
    lastMaintenance: '2024-10-25',
    nextMaintenance: '2025-01-25',
    maintenancePriority: 'Low',
    usageHours: 980,
  },
  {
    id: 'eq-8',
    name: 'Kettlebell Set (8-32kg)',
    category: 'Free Weights',
    manufacturer: 'Wolverson',
    model: 'Competition KB',
    serialNumber: 'WV-KB-2022-201',
    purchaseDate: '2022-11-01',
    warrantyExpiry: '2024-11-01',
    status: 'Operational',
    location: 'Functional Training',
    lastMaintenance: '2024-09-01',
    nextMaintenance: '2025-03-01',
    maintenancePriority: 'Low',
  },
  {
    id: 'eq-9',
    name: 'Elliptical Trainer',
    category: 'Cardio',
    manufacturer: 'Precor',
    model: 'EFX 885',
    serialNumber: 'PR-EL-2023-045',
    purchaseDate: '2023-02-15',
    warrantyExpiry: '2026-02-15',
    status: 'Maintenance Required',
    location: 'Cardio Zone A',
    lastMaintenance: '2024-08-15',
    nextMaintenance: '2024-11-25',
    maintenancePriority: 'Medium',
    usageHours: 2100,
    notes: 'Squeaking pedal - needs inspection',
  },
  {
    id: 'eq-10',
    name: 'Battle Ropes',
    category: 'Functional',
    manufacturer: 'TRX',
    model: 'Heavy Duty 50ft',
    serialNumber: 'TRX-BR-2023-089',
    purchaseDate: '2023-05-01',
    warrantyExpiry: '2025-05-01',
    status: 'Operational',
    location: 'Functional Training',
    lastMaintenance: '2024-11-01',
    nextMaintenance: '2025-02-01',
    maintenancePriority: 'Low',
  },
  {
    id: 'eq-11',
    name: 'Spin Bike',
    category: 'Cardio',
    manufacturer: 'Schwinn',
    model: 'IC4',
    serialNumber: 'SCH-SB-2023-112',
    purchaseDate: '2023-03-20',
    warrantyExpiry: '2026-03-20',
    status: 'Operational',
    location: 'Spin Studio',
    lastMaintenance: '2024-10-30',
    nextMaintenance: '2025-01-30',
    maintenancePriority: 'Low',
    usageHours: 1450,
  },
  {
    id: 'eq-12',
    name: 'Bench Press Station',
    category: 'Strength',
    manufacturer: 'Hammer Strength',
    model: 'Olympic Flat Bench',
    serialNumber: 'HS-BP-2022-067',
    purchaseDate: '2022-07-15',
    warrantyExpiry: '2027-07-15',
    status: 'Operational',
    location: 'Free Weights Area',
    lastMaintenance: '2024-10-01',
    nextMaintenance: '2025-01-01',
    maintenancePriority: 'Low',
  },
  {
    id: 'eq-13',
    name: 'Foam Roller Set',
    category: 'Stretching',
    manufacturer: 'TriggerPoint',
    model: 'GRID Foam Roller',
    serialNumber: 'TP-FR-2023-201',
    purchaseDate: '2023-06-01',
    warrantyExpiry: '2024-06-01',
    status: 'Operational',
    location: 'Stretching Area',
    lastMaintenance: '2024-11-10',
    nextMaintenance: '2025-05-10',
    maintenancePriority: 'Low',
  },
  {
    id: 'eq-14',
    name: 'Boxing Heavy Bag',
    category: 'Group Fitness',
    manufacturer: 'Everlast',
    model: 'PowerCore 100lb',
    serialNumber: 'EV-HB-2022-145',
    purchaseDate: '2022-08-20',
    warrantyExpiry: '2024-08-20',
    status: 'Maintenance Required',
    location: 'Boxing Studio',
    lastMaintenance: '2024-07-01',
    nextMaintenance: '2024-11-18',
    maintenancePriority: 'Medium',
    notes: 'Chain needs tightening',
  },
  {
    id: 'eq-15',
    name: 'Pull-up Bar Station',
    category: 'Functional',
    manufacturer: 'Rogue Fitness',
    model: 'Standalone Rig',
    serialNumber: 'RF-PU-2023-034',
    purchaseDate: '2023-01-10',
    warrantyExpiry: '2028-01-10',
    status: 'Out of Service',
    location: 'CrossFit Area',
    lastMaintenance: '2024-09-20',
    nextMaintenance: '2024-11-30',
    maintenancePriority: 'Critical',
    notes: 'Welding crack detected - safety hazard',
  },
];
