import { User } from 'lucide-react';

export type MembershipTier = 'Basic' | 'Premium' | 'VIP' | 'Trial';
export type MembershipStatus = 'Active' | 'Expired' | 'Suspended' | 'Pending';
export type Gender = 'Male' | 'Female' | 'Other';

export interface GymMember {
  id: string;
  name: string;
  email: string;
  phone: string;
  avatarUrl: string;
  membershipTier: MembershipTier;
  membershipStatus: MembershipStatus;
  joinedDate: string;
  expiryDate: string;
  gender: Gender;
  age: number;
  emergencyContact: string;
  emergencyPhone: string;
  medicalNotes?: string;
  assignedTrainerId?: string;
}

export const gymMembers: GymMember[] = [
  {
    id: 'gm-1',
    name: 'Sarah Johnson',
    email: 'sarah.j@email.com',
    phone: '+1-555-0101',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    membershipTier: 'Premium',
    membershipStatus: 'Active',
    joinedDate: '2024-01-15',
    expiryDate: '2025-01-15',
    gender: 'Female',
    age: 28,
    emergencyContact: 'John Johnson',
    emergencyPhone: '+1-555-0102',
    assignedTrainerId: 'tr-1',
  },
  {
    id: 'gm-2',
    name: 'Michael Chen',
    email: 'mchen@email.com',
    phone: '+1-555-0103',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    membershipTier: 'VIP',
    membershipStatus: 'Active',
    joinedDate: '2023-06-10',
    expiryDate: '2025-06-10',
    gender: 'Male',
    age: 35,
    emergencyContact: 'Lisa Chen',
    emergencyPhone: '+1-555-0104',
    assignedTrainerId: 'tr-2',
  },
  {
    id: 'gm-3',
    name: 'Emma Williams',
    email: 'emma.w@email.com',
    phone: '+1-555-0105',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    membershipTier: 'Basic',
    membershipStatus: 'Active',
    joinedDate: '2024-03-20',
    expiryDate: '2025-03-20',
    gender: 'Female',
    age: 22,
    emergencyContact: 'David Williams',
    emergencyPhone: '+1-555-0106',
  },
  {
    id: 'gm-4',
    name: 'James Rodriguez',
    email: 'j.rodriguez@email.com',
    phone: '+1-555-0107',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    membershipTier: 'Premium',
    membershipStatus: 'Active',
    joinedDate: '2024-02-01',
    expiryDate: '2025-02-01',
    gender: 'Male',
    age: 31,
    emergencyContact: 'Maria Rodriguez',
    emergencyPhone: '+1-555-0108',
    assignedTrainerId: 'tr-3',
  },
  {
    id: 'gm-5',
    name: 'Olivia Brown',
    email: 'olivia.b@email.com',
    phone: '+1-555-0109',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia',
    membershipTier: 'Trial',
    membershipStatus: 'Active',
    joinedDate: '2024-11-01',
    expiryDate: '2024-12-01',
    gender: 'Female',
    age: 26,
    emergencyContact: 'Robert Brown',
    emergencyPhone: '+1-555-0110',
  },
  {
    id: 'gm-6',
    name: 'David Kim',
    email: 'dkim@email.com',
    phone: '+1-555-0111',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    membershipTier: 'VIP',
    membershipStatus: 'Active',
    joinedDate: '2023-09-15',
    expiryDate: '2025-09-15',
    gender: 'Male',
    age: 42,
    emergencyContact: 'Jennifer Kim',
    emergencyPhone: '+1-555-0112',
    assignedTrainerId: 'tr-1',
  },
  {
    id: 'gm-7',
    name: 'Sophia Martinez',
    email: 'sophia.m@email.com',
    phone: '+1-555-0113',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophia',
    membershipTier: 'Premium',
    membershipStatus: 'Expired',
    joinedDate: '2023-11-10',
    expiryDate: '2024-11-10',
    gender: 'Female',
    age: 29,
    emergencyContact: 'Carlos Martinez',
    emergencyPhone: '+1-555-0114',
  },
  {
    id: 'gm-8',
    name: 'Daniel Anderson',
    email: 'dan.anderson@email.com',
    phone: '+1-555-0115',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel',
    membershipTier: 'Basic',
    membershipStatus: 'Active',
    joinedDate: '2024-04-05',
    expiryDate: '2025-04-05',
    gender: 'Male',
    age: 24,
    emergencyContact: 'Susan Anderson',
    emergencyPhone: '+1-555-0116',
    assignedTrainerId: 'tr-2',
  },
  {
    id: 'gm-9',
    name: 'Isabella Taylor',
    email: 'isabella.t@email.com',
    phone: '+1-555-0117',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella',
    membershipTier: 'Premium',
    membershipStatus: 'Suspended',
    joinedDate: '2024-01-20',
    expiryDate: '2025-01-20',
    gender: 'Female',
    age: 33,
    emergencyContact: 'Michael Taylor',
    emergencyPhone: '+1-555-0118',
    medicalNotes: 'Knee injury - avoid high impact exercises',
  },
  {
    id: 'gm-10',
    name: 'Ryan Thompson',
    email: 'ryan.t@email.com',
    phone: '+1-555-0119',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ryan',
    membershipTier: 'VIP',
    membershipStatus: 'Active',
    joinedDate: '2023-07-01',
    expiryDate: '2025-07-01',
    gender: 'Male',
    age: 38,
    emergencyContact: 'Amy Thompson',
    emergencyPhone: '+1-555-0120',
    assignedTrainerId: 'tr-3',
  },
  {
    id: 'gm-11',
    name: 'Ava Garcia',
    email: 'ava.garcia@email.com',
    phone: '+1-555-0121',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ava',
    membershipTier: 'Basic',
    membershipStatus: 'Active',
    joinedDate: '2024-05-12',
    expiryDate: '2025-05-12',
    gender: 'Female',
    age: 27,
    emergencyContact: 'Jose Garcia',
    emergencyPhone: '+1-555-0122',
  },
  {
    id: 'gm-12',
    name: 'William Lee',
    email: 'will.lee@email.com',
    phone: '+1-555-0123',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=William',
    membershipTier: 'Premium',
    membershipStatus: 'Active',
    joinedDate: '2024-02-28',
    expiryDate: '2025-02-28',
    gender: 'Male',
    age: 30,
    emergencyContact: 'Sarah Lee',
    emergencyPhone: '+1-555-0124',
    assignedTrainerId: 'tr-1',
  },
  {
    id: 'gm-13',
    name: 'Mia Wilson',
    email: 'mia.wilson@email.com',
    phone: '+1-555-0125',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mia',
    membershipTier: 'Trial',
    membershipStatus: 'Pending',
    joinedDate: '2024-11-10',
    expiryDate: '2024-12-10',
    gender: 'Female',
    age: 25,
    emergencyContact: 'James Wilson',
    emergencyPhone: '+1-555-0126',
  },
  {
    id: 'gm-14',
    name: 'Ethan Harris',
    email: 'ethan.h@email.com',
    phone: '+1-555-0127',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ethan',
    membershipTier: 'VIP',
    membershipStatus: 'Active',
    joinedDate: '2023-08-20',
    expiryDate: '2025-08-20',
    gender: 'Male',
    age: 45,
    emergencyContact: 'Emily Harris',
    emergencyPhone: '+1-555-0128',
    assignedTrainerId: 'tr-2',
  },
  {
    id: 'gm-15',
    name: 'Charlotte Clark',
    email: 'charlotte.c@email.com',
    phone: '+1-555-0129',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Charlotte',
    membershipTier: 'Premium',
    membershipStatus: 'Active',
    joinedDate: '2024-03-15',
    expiryDate: '2025-03-15',
    gender: 'Female',
    age: 32,
    emergencyContact: 'Daniel Clark',
    emergencyPhone: '+1-555-0130',
    assignedTrainerId: 'tr-3',
  },
];
