import { MembershipTier } from './gym-members';

export type BillingCycle = 'Monthly' | 'Quarterly' | 'Yearly';
export type PaymentStatus = 'Paid' | 'Pending' | 'Overdue' | 'Failed';

export interface MembershipPlan {
  id: string;
  name: MembershipTier;
  description: string;
  features: string[];
  monthlyPrice: number;
  quarterlyPrice: number;
  yearlyPrice: number;
  classCredits: number; // per month, -1 for unlimited
  personalTrainingSessions: number; // per month
  guestPasses: number; // per month
  accessHours: string;
  priority: number; // for sorting
}

export interface MembershipSubscription {
  id: string;
  memberId: string;
  planId: string;
  billingCycle: BillingCycle;
  startDate: string;
  endDate: string;
  renewalDate: string;
  amount: number;
  paymentStatus: PaymentStatus;
  autoRenew: boolean;
  lastPaymentDate?: string;
  nextPaymentDate?: string;
}

export const membershipPlans: MembershipPlan[] = [
  {
    id: 'plan-1',
    name: 'Trial',
    description: '1-month trial membership to explore our facilities',
    features: [
      'Access to gym floor',
      'Group fitness classes (5 credits/month)',
      'Locker room access',
      'Fitness assessment',
    ],
    monthlyPrice: 29,
    quarterlyPrice: 0,
    yearlyPrice: 0,
    classCredits: 5,
    personalTrainingSessions: 0,
    guestPasses: 0,
    accessHours: '6:00 AM - 10:00 PM',
    priority: 1,
  },
  {
    id: 'plan-2',
    name: 'Basic',
    description: 'Essential membership for regular gym-goers',
    features: [
      'Unlimited gym floor access',
      'Group fitness classes (15 credits/month)',
      'Locker room with shower',
      'Mobile app access',
      '1 guest pass/month',
    ],
    monthlyPrice: 49,
    quarterlyPrice: 135,
    yearlyPrice: 499,
    classCredits: 15,
    personalTrainingSessions: 0,
    guestPasses: 1,
    accessHours: '24/7',
    priority: 2,
  },
  {
    id: 'plan-3',
    name: 'Premium',
    description: 'Full-featured membership with training sessions',
    features: [
      'Unlimited gym floor access',
      'Unlimited group fitness classes',
      '2 personal training sessions/month',
      'Locker room with amenities',
      'Mobile app access',
      '3 guest passes/month',
      'Towel service',
      'Nutritional consultation (quarterly)',
    ],
    monthlyPrice: 99,
    quarterlyPrice: 270,
    yearlyPrice: 999,
    classCredits: -1,
    personalTrainingSessions: 2,
    guestPasses: 3,
    accessHours: '24/7',
    priority: 3,
  },
  {
    id: 'plan-4',
    name: 'VIP',
    description: 'Premium membership with exclusive perks',
    features: [
      'Unlimited gym floor access',
      'Unlimited group fitness classes',
      '4 personal training sessions/month',
      'VIP locker room access',
      'Mobile app access',
      '5 guest passes/month',
      'Towel & laundry service',
      'Monthly nutritional consultation',
      'Monthly massage therapy',
      'Priority class booking',
      'Exclusive VIP events',
      'Private training area access',
    ],
    monthlyPrice: 199,
    quarterlyPrice: 540,
    yearlyPrice: 1999,
    classCredits: -1,
    personalTrainingSessions: 4,
    guestPasses: 5,
    accessHours: '24/7',
    priority: 4,
  },
];

export const membershipSubscriptions: MembershipSubscription[] = [
  {
    id: 'sub-1',
    memberId: 'gm-1',
    planId: 'plan-3',
    billingCycle: 'Yearly',
    startDate: '2024-01-15',
    endDate: '2025-01-15',
    renewalDate: '2025-01-15',
    amount: 999,
    paymentStatus: 'Paid',
    autoRenew: true,
    lastPaymentDate: '2024-01-15',
    nextPaymentDate: '2025-01-15',
  },
  {
    id: 'sub-2',
    memberId: 'gm-2',
    planId: 'plan-4',
    billingCycle: 'Yearly',
    startDate: '2023-06-10',
    endDate: '2025-06-10',
    renewalDate: '2025-06-10',
    amount: 1999,
    paymentStatus: 'Paid',
    autoRenew: true,
    lastPaymentDate: '2024-06-10',
    nextPaymentDate: '2025-06-10',
  },
  {
    id: 'sub-3',
    memberId: 'gm-3',
    planId: 'plan-2',
    billingCycle: 'Monthly',
    startDate: '2024-03-20',
    endDate: '2025-03-20',
    renewalDate: '2024-12-20',
    amount: 49,
    paymentStatus: 'Paid',
    autoRenew: true,
    lastPaymentDate: '2024-11-20',
    nextPaymentDate: '2024-12-20',
  },
  {
    id: 'sub-4',
    memberId: 'gm-4',
    planId: 'plan-3',
    billingCycle: 'Quarterly',
    startDate: '2024-02-01',
    endDate: '2025-02-01',
    renewalDate: '2025-02-01',
    amount: 270,
    paymentStatus: 'Paid',
    autoRenew: true,
    lastPaymentDate: '2024-11-01',
    nextPaymentDate: '2025-02-01',
  },
  {
    id: 'sub-5',
    memberId: 'gm-5',
    planId: 'plan-1',
    billingCycle: 'Monthly',
    startDate: '2024-11-01',
    endDate: '2024-12-01',
    renewalDate: '2024-12-01',
    amount: 29,
    paymentStatus: 'Paid',
    autoRenew: false,
    lastPaymentDate: '2024-11-01',
    nextPaymentDate: '2024-12-01',
  },
  {
    id: 'sub-6',
    memberId: 'gm-6',
    planId: 'plan-4',
    billingCycle: 'Yearly',
    startDate: '2023-09-15',
    endDate: '2025-09-15',
    renewalDate: '2025-09-15',
    amount: 1999,
    paymentStatus: 'Paid',
    autoRenew: true,
    lastPaymentDate: '2024-09-15',
    nextPaymentDate: '2025-09-15',
  },
  {
    id: 'sub-7',
    memberId: 'gm-7',
    planId: 'plan-3',
    billingCycle: 'Monthly',
    startDate: '2023-11-10',
    endDate: '2024-11-10',
    renewalDate: '2024-11-10',
    amount: 99,
    paymentStatus: 'Overdue',
    autoRenew: false,
    lastPaymentDate: '2024-10-10',
  },
  {
    id: 'sub-8',
    memberId: 'gm-8',
    planId: 'plan-2',
    billingCycle: 'Yearly',
    startDate: '2024-04-05',
    endDate: '2025-04-05',
    renewalDate: '2025-04-05',
    amount: 499,
    paymentStatus: 'Paid',
    autoRenew: true,
    lastPaymentDate: '2024-04-05',
    nextPaymentDate: '2025-04-05',
  },
  {
    id: 'sub-9',
    memberId: 'gm-9',
    planId: 'plan-3',
    billingCycle: 'Monthly',
    startDate: '2024-01-20',
    endDate: '2025-01-20',
    renewalDate: '2024-12-20',
    amount: 99,
    paymentStatus: 'Failed',
    autoRenew: true,
    lastPaymentDate: '2024-10-20',
    nextPaymentDate: '2024-11-20',
  },
  {
    id: 'sub-10',
    memberId: 'gm-10',
    planId: 'plan-4',
    billingCycle: 'Monthly',
    startDate: '2023-07-01',
    endDate: '2025-07-01',
    renewalDate: '2024-12-01',
    amount: 199,
    paymentStatus: 'Paid',
    autoRenew: true,
    lastPaymentDate: '2024-11-01',
    nextPaymentDate: '2024-12-01',
  },
  {
    id: 'sub-11',
    memberId: 'gm-11',
    planId: 'plan-2',
    billingCycle: 'Monthly',
    startDate: '2024-05-12',
    endDate: '2025-05-12',
    renewalDate: '2024-12-12',
    amount: 49,
    paymentStatus: 'Paid',
    autoRenew: true,
    lastPaymentDate: '2024-11-12',
    nextPaymentDate: '2024-12-12',
  },
  {
    id: 'sub-12',
    memberId: 'gm-12',
    planId: 'plan-3',
    billingCycle: 'Quarterly',
    startDate: '2024-02-28',
    endDate: '2025-02-28',
    renewalDate: '2024-11-28',
    amount: 270,
    paymentStatus: 'Pending',
    autoRenew: true,
    lastPaymentDate: '2024-08-28',
    nextPaymentDate: '2024-11-28',
  },
  {
    id: 'sub-13',
    memberId: 'gm-13',
    planId: 'plan-1',
    billingCycle: 'Monthly',
    startDate: '2024-11-10',
    endDate: '2024-12-10',
    renewalDate: '2024-12-10',
    amount: 29,
    paymentStatus: 'Pending',
    autoRenew: false,
    nextPaymentDate: '2024-12-10',
  },
  {
    id: 'sub-14',
    memberId: 'gm-14',
    planId: 'plan-4',
    billingCycle: 'Yearly',
    startDate: '2023-08-20',
    endDate: '2025-08-20',
    renewalDate: '2025-08-20',
    amount: 1999,
    paymentStatus: 'Paid',
    autoRenew: true,
    lastPaymentDate: '2024-08-20',
    nextPaymentDate: '2025-08-20',
  },
  {
    id: 'sub-15',
    memberId: 'gm-15',
    planId: 'plan-3',
    billingCycle: 'Monthly',
    startDate: '2024-03-15',
    endDate: '2025-03-15',
    renewalDate: '2024-12-15',
    amount: 99,
    paymentStatus: 'Paid',
    autoRenew: true,
    lastPaymentDate: '2024-11-15',
    nextPaymentDate: '2024-12-15',
  },
];
