import { Priority, priorities } from './priorities';
import { Health, health, Project, projects } from './projects';
import { User, users } from './users';

export type InitiativeStatus = 'active' | 'planned' | 'completed' | 'canceled';

export interface Initiative {
   id: string;
   name: string;
   description?: string;
   /** Emoji used as the initiative icon. */
   icon: string;
   status: InitiativeStatus;
   priority: Priority;
   owner?: User;
   /** Team steering the initiative (see mock-data/teams) — Linear "Lead team". */
   leadTeamId?: string;
   /** Target label shown in the list ("Q3 2026", "Sep 30th", …). */
   target?: string;
   health: Health;
   projectIds: string[];
   createdAt: string;
}

export const INITIATIVE_STATUS_META: Record<InitiativeStatus, { label: string; color: string }> = {
   active: { label: 'Active', color: '#f2c94c' },
   planned: { label: 'Planned', color: '#95a2b3' },
   completed: { label: 'Completed', color: '#5e6ad2' },
   canceled: { label: 'Canceled', color: '#95a2b3' },
};

const noUpdate = health[0];
const byId = (id: string): Health => health.find((entry) => entry.id === id) ?? noUpdate;

/**
 * Workspace initiatives (Linear "Initiatives" page). Fake data around the
 * LNDev UI component-library storyline; projects reference mock-data/projects.
 */
export const initiatives: Initiative[] = [
   {
      id: 'component-platform',
      name: 'Q3 — Ship the component platform',
      description: 'Deliver the full core component suite with stable APIs and docs.',
      icon: '🧱',
      status: 'active',
      priority: priorities[0],
      owner: users[0],
      target: 'Q3 2026',
      health: byId('on-track'),
      projectIds: ['1', '2', '3', '7', '13', '19'],
      createdAt: '2026-04-02',
   },
   {
      id: 'quality-accessibility',
      name: 'Q3 — Raise quality and accessibility',
      description: 'WCAG AA across the library, visual regression coverage and audits.',
      icon: '♿',
      status: 'active',
      priority: priorities[2],
      owner: users[3],
      target: 'Q3 2026',
      health: byId('at-risk'),
      projectIds: ['4', '10', '16', '22'],
      createdAt: '2026-04-11',
   },
   {
      id: 'design-system-adoption',
      name: 'Q4 — Grow design system adoption',
      description: 'Templates, starter kits and integrations that drive adoption.',
      icon: '🌱',
      status: 'active',
      priority: priorities[3],
      owner: users[1],
      target: 'Q4 2026',
      health: noUpdate,
      projectIds: ['5', '11', '17', '23'],
      createdAt: '2026-05-06',
   },
   {
      id: 'performance-lab',
      name: 'Q3 — Cut bundle size in half',
      description: 'Tree-shakeable exports, lazy primitives and a leaner runtime.',
      icon: '⚡',
      status: 'active',
      priority: priorities[1],
      owner: users[4],
      leadTeamId: 'PERF',
      target: 'Q3 2026',
      health: byId('on-track'),
      projectIds: ['6', '12', '18'],
      createdAt: '2026-04-20',
   },
   {
      id: 'docs-refresh',
      name: 'Q3 — Documentation refresh',
      icon: '📚',
      status: 'active',
      priority: priorities[0],
      owner: users[6],
      target: 'Q3 2026',
      health: noUpdate,
      projectIds: ['8', '14'],
      createdAt: '2026-05-14',
   },
   {
      id: 'theming-engine',
      name: 'Q4 — Next-gen theming engine',
      description: 'Design tokens, runtime variants and a visual theme builder.',
      icon: '🎨',
      status: 'planned',
      priority: priorities[2],
      owner: users[2],
      leadTeamId: 'DESIGN',
      target: 'Q4 2026',
      health: noUpdate,
      projectIds: ['2', '9', '15'],
      createdAt: '2026-06-01',
   },
   {
      id: 'mobile-primitives',
      name: 'Q4 — Mobile-first primitives',
      description: 'Touch targets, gestures and adaptive layouts for small screens.',
      icon: '📱',
      status: 'planned',
      priority: priorities[0],
      owner: users[5],
      target: 'Q4 2026',
      health: noUpdate,
      projectIds: ['20', '24'],
      createdAt: '2026-06-09',
   },
   {
      id: 'playground',
      name: 'Q4 — Interactive component playground',
      icon: '🛝',
      status: 'planned',
      priority: priorities[4],
      owner: users[7],
      target: 'Sep 30th',
      health: noUpdate,
      projectIds: ['21', '25'],
      createdAt: '2026-06-18',
   },
   {
      id: 'backlog-grooming',
      name: 'Backlog — Community requests',
      icon: '🧺',
      status: 'planned',
      priority: priorities[0],
      target: 'Q4 2026',
      health: noUpdate,
      projectIds: ['9', '24'],
      createdAt: '2026-06-25',
   },
   {
      id: 'v2-launch',
      name: 'Q2 — Launch LNDev UI v2',
      description: 'Rebrand, new website and the v2 breaking-changes migration guide.',
      icon: '🚀',
      status: 'completed',
      priority: priorities[1],
      owner: users[0],
      target: 'Q2 2026',
      health: byId('on-track'),
      projectIds: ['1', '5', '8'],
      createdAt: '2026-01-12',
   },
   {
      id: 'infra-migration',
      name: 'Q2 — Move CI to self-hosted runners',
      icon: '🏗️',
      status: 'completed',
      priority: priorities[3],
      owner: users[8],
      target: 'Q2 2026',
      health: byId('on-track'),
      projectIds: ['12'],
      createdAt: '2026-02-03',
   },
   {
      id: 'storybook-migration-first-pass',
      name: 'Storybook migration — first pass',
      description:
         'Move every story to the new format in one sweep. Called off: the codemod choked on custom decorators, replaced by the incremental second pass.',
      icon: '📖',
      status: 'canceled',
      priority: priorities[2],
      owner: users[2],
      leadTeamId: 'CORE',
      target: 'Sep 30th',
      health: noUpdate,
      projectIds: ['3', '7'],
      createdAt: '2026-05-02',
   },
   {
      id: 'storybook-migration-second-pass',
      name: 'Storybook migration — second pass',
      description:
         'Same goal, sliced package by package: each chunk migrates, ships and locks before the next one starts.',
      icon: '📖',
      status: 'planned',
      priority: priorities[2],
      owner: users[2],
      leadTeamId: 'CORE',
      target: 'Sep 30th',
      health: noUpdate,
      projectIds: ['13', '19'],
      createdAt: '2026-06-28',
   },
   {
      id: 'a11y-certification',
      name: 'Q4 — WCAG AA certification, third-party audited',
      description:
         'External audit across the 40 core components, remediation sprints, and the public conformance report.',
      icon: '🏅',
      status: 'active',
      priority: priorities[1],
      owner: users[9],
      leadTeamId: 'UX',
      target: 'Q4 2026',
      health: byId('at-risk'),
      projectIds: ['4', '10', '16'],
      createdAt: '2026-05-19',
   },
   {
      id: 'charts-v2',
      name: 'Q4 — Charts v2 on the new canvas renderer',
      description:
         'Rebuild the charts package on the shared canvas renderer: 10× point budget, streaming data, one theming pipeline.',
      icon: '📈',
      status: 'active',
      priority: priorities[2],
      owner: users[10],
      leadTeamId: 'PERF',
      target: 'Q4 2026',
      health: byId('on-track'),
      projectIds: ['6', '18'],
      createdAt: '2026-05-27',
   },
   {
      id: 'templates-marketplace',
      name: 'Q4 — Community templates marketplace',
      description:
         'Submission flow, review pipeline and revenue share for community-built templates and blocks.',
      icon: '🛍️',
      status: 'active',
      priority: priorities[3],
      owner: users[11],
      leadTeamId: 'CORE',
      target: 'Oct 15th',
      health: byId('off-track'),
      projectIds: ['5', '11', '17'],
      createdAt: '2026-06-03',
   },
   {
      id: 'i18n-rtl',
      name: 'Q4 — First-class RTL and logical properties',
      description:
         'Every component audited for logical properties, an RTL visual test lane, and mirrored icon variants.',
      icon: '🌍',
      status: 'active',
      priority: priorities[2],
      owner: users[12],
      leadTeamId: 'UX',
      target: 'Q4 2026',
      health: byId('on-track'),
      projectIds: ['10', '16'],
      createdAt: '2026-06-11',
   },
   {
      id: 'telemetry-dashboard',
      name: 'Q3 — Component adoption telemetry, opt-in',
      description:
         'Anonymous, opt-in usage signals feeding the public adoption dashboard — one switch, zero calls when off.',
      icon: '📊',
      status: 'active',
      priority: priorities[3],
      owner: users[13],
      leadTeamId: 'DATA',
      target: 'Q3 2026',
      health: byId('on-track'),
      projectIds: ['14', '20'],
      createdAt: '2026-04-28',
   },
   {
      id: 'native-mobile-kit',
      name: 'Q1 2027 — Native mobile kit (RN bindings)',
      description:
         'React Native bindings for the 12 most-used primitives, sharing tokens with the web library.',
      icon: '📲',
      status: 'planned',
      priority: priorities[2],
      owner: users[14],
      leadTeamId: 'MOBILE',
      target: 'Q1 2027',
      health: noUpdate,
      projectIds: ['20'],
      createdAt: '2026-07-02',
   },
   {
      id: 'design-linter',
      name: 'Q1 2027 — Design linter for Figma files',
      description:
         'A plugin that flags off-token colors, off-grid spacing and detached components before handoff.',
      icon: '🧹',
      status: 'planned',
      priority: priorities[3],
      owner: users[15],
      leadTeamId: 'DESIGN',
      target: 'Q1 2027',
      health: noUpdate,
      projectIds: ['2', '15'],
      createdAt: '2026-07-08',
   },
   {
      id: 'ssr-streaming',
      name: 'Q4 — Zero-flash SSR streaming support',
      description:
         'Every component renders server-side without hydration mismatch, themes resolve before first paint.',
      icon: '🌊',
      status: 'planned',
      priority: priorities[1],
      owner: users[16],
      leadTeamId: 'PERF',
      target: 'Q4 2026',
      health: noUpdate,
      projectIds: ['6', '12'],
      createdAt: '2026-07-15',
   },
   {
      id: 'docs-search-ai',
      name: 'Q4 — Ask-the-docs search',
      description:
         'Semantic search over docs, guides and API references, with copy-ready code answers.',
      icon: '🔎',
      status: 'planned',
      priority: priorities[3],
      owner: users[17],
      leadTeamId: 'DATA',
      target: 'Q4 2026',
      health: noUpdate,
      projectIds: ['8', '14'],
      createdAt: '2026-07-21',
   },
   {
      id: 'enterprise-theming',
      name: 'Q1 2027 — Enterprise theming: multi-brand workspaces',
      description:
         'One workspace, many brands: scoped token sets, brand switching at runtime and per-tenant overrides.',
      icon: '🏢',
      status: 'planned',
      priority: priorities[2],
      owner: users[18],
      leadTeamId: 'DESIGN',
      target: 'Q1 2027',
      health: noUpdate,
      projectIds: ['2', '9'],
      createdAt: '2026-07-29',
   },
   {
      id: 'q1-stability',
      name: 'Q1 — Zero-P0 quarter',
      description:
         'The bug-debt quarter: every open P0/P1 closed, flaky tests quarantined, error budget policy adopted.',
      icon: '🧯',
      status: 'completed',
      priority: priorities[1],
      owner: users[19],
      leadTeamId: 'CORE',
      target: 'Q1 2026',
      health: byId('on-track'),
      projectIds: ['3', '7'],
      createdAt: '2025-12-10',
   },
   {
      id: 'q1-docs-versioning',
      name: 'Q1 — Versioned documentation',
      description: 'Docs frozen per major version, with an always-current canonical.',
      icon: '🗂️',
      status: 'completed',
      priority: priorities[3],
      owner: users[20],
      leadTeamId: 'DATA',
      target: 'Q1 2026',
      health: byId('on-track'),
      projectIds: ['8'],
      createdAt: '2026-01-06',
   },
   {
      id: 'q2-icon-library',
      name: 'Q2 — Icon library: 400 icons, three sizes',
      description: 'The full icon set redrawn on the shared grid, shipped as its own package.',
      icon: '✒️',
      status: 'completed',
      priority: priorities[2],
      owner: users[21],
      leadTeamId: 'DESIGN',
      target: 'Q2 2026',
      health: byId('on-track'),
      projectIds: ['15'],
      createdAt: '2026-02-17',
   },
   {
      id: 'web-components-bridge',
      name: 'Web Components bridge',
      description:
         'Called off after the spike: the bridge doubled the maintenance surface for <2% of demand. Revisit if custom-elements demand grows.',
      icon: '🌉',
      status: 'canceled',
      priority: priorities[4],
      owner: users[7],
      leadTeamId: 'CORE',
      target: 'Q3 2026',
      health: noUpdate,
      projectIds: ['13'],
      createdAt: '2026-03-12',
   },
   {
      id: 'legacy-ie-support',
      name: 'Extended legacy-browser support tier',
      description:
         'Canceled with the v2 launch: the paid legacy tier attracted three prospects, none converted.',
      icon: '🦖',
      status: 'canceled',
      priority: priorities[0],
      owner: users[5],
      leadTeamId: 'PERF',
      target: 'Q2 2026',
      health: noUpdate,
      projectIds: ['12'],
      createdAt: '2026-02-25',
   },
];

/** Initiatives a team sees: it leads them, or one of its projects is inside. */
export function getTeamInitiatives(teamId: string): Initiative[] {
   return initiatives.filter(
      (initiative) =>
         initiative.leadTeamId === teamId ||
         getInitiativeProjects(initiative).some((project) => project.teamId === teamId)
   );
}

export function getInitiativeById(id: string): Initiative | undefined {
   return initiatives.find((initiative) => initiative.id === id);
}

export function getInitiativeProjects(initiative: Initiative): Project[] {
   return initiative.projectIds
      .map((id) => projects.find((project) => project.id === id))
      .filter((project): project is Project => Boolean(project));
}

/** Projects considered "completed" for the n / m counter. */
export function countCompletedProjects(initiative: Initiative): number {
   return getInitiativeProjects(initiative).filter(
      (project) => project.status.category === 'completed' || project.percentComplete >= 100
   ).length;
}

/* --------------------------- seed-based expansion -------------------------- */
/*
 * Bulk of the portfolio, one tuple per initiative (same trick as issues.ts):
 * [id, name, icon, status, priorityIdx, ownerIdx | null, leadTeamId | null,
 *  target, healthId | null (null = no update), projectIds, createdAt,
 *  description?]
 */

type InitiativeSeed = [
   id: string,
   name: string,
   icon: string,
   status: InitiativeStatus,
   priorityIdx: number,
   ownerIdx: number | null,
   leadTeamId: string | null,
   target: string,
   healthId: string | null,
   projectIds: string[],
   createdAt: string,
   description?: string,
];

const seeds: InitiativeSeed[] = [
   /* --------------------------------- active -------------------------------- */
   [
      'form-engine',
      'Q4 — Declarative form engine',
      '🧾',
      'active',
      2,
      3,
      'CORE',
      'Q4 2026',
      'on-track',
      ['1', '3'],
      '2026-06-20',
      'Schema-driven forms: validation, wizard flows and persistence handled by the library, not the app.',
   ],
   [
      'visual-regression-net',
      'Q4 — Visual regression safety net',
      '📸',
      'active',
      1,
      9,
      'DESIGN',
      'Q4 2026',
      'on-track',
      ['4', '15'],
      '2026-06-24',
      'Every component state snapshotted per theme and density — a diff gate on every PR.',
   ],
   [
      'edge-rendering',
      'Q4 — Edge-rendered docs, sub-second everywhere',
      '🌐',
      'active',
      2,
      10,
      'PERF',
      'Q4 2026',
      'at-risk',
      ['8', '12'],
      '2026-07-01',
      'Docs served from the edge with per-region caches; p95 TTFB under 200ms on every continent.',
   ],
   [
      'keyboard-first',
      'Q4 — Keyboard-first navigation pass',
      '⌨️',
      'active',
      2,
      11,
      'UX',
      'Q4 2026',
      'on-track',
      ['10', '16'],
      '2026-07-05',
      'Every flow completable without a pointer, with visible focus and documented shortcuts.',
   ],
   [
      'usage-insights-v2',
      'Q4 — Usage insights v2 for workspace admins',
      '🔬',
      'active',
      3,
      12,
      'DATA',
      'Q4 2026',
      null,
      ['14', '20'],
      '2026-07-12',
      'Per-component adoption, upgrade blockers and dead-code candidates, visible to workspace admins.',
   ],
   [
      'gesture-library',
      'Q4 — Unified gesture library',
      '👆',
      'active',
      2,
      13,
      'MOBILE',
      'Q4 2026',
      'on-track',
      ['20'],
      '2026-07-18',
      'One arbitration layer for swipe, drag and long-press across every touch component.',
   ],
   [
      'docs-i18n',
      'Q4 — Docs in four languages',
      '🗣️',
      'active',
      3,
      14,
      'UX',
      'Q4 2026',
      'off-track',
      ['8', '14'],
      '2026-07-22',
      'Machine-assisted translation pipeline with human review for the top four community languages.',
   ],
   [
      'release-train',
      'Q4 — Predictable monthly release train',
      '🚆',
      'active',
      1,
      15,
      'CORE',
      'Q4 2026',
      'on-track',
      ['7', '13'],
      '2026-07-26',
      'A minor on the first Tuesday of every month, breaking changes only in majors, betas cut two weeks ahead.',
   ],
   [
      'a11y-audit-tooling',
      'Q3 — Automated a11y audit in CI',
      '🤖',
      'active',
      2,
      16,
      'UX',
      'Q3 2026',
      'at-risk',
      ['4', '10'],
      '2026-05-08',
      'Axe-based CI lane with a per-component allowlist that only ever shrinks.',
   ],
   [
      'sandbox-persistence',
      'Q3 — Playground projects that survive reloads',
      '💾',
      'active',
      3,
      17,
      'CORE',
      'Q3 2026',
      'on-track',
      ['5', '11'],
      '2026-05-16',
      'Named sandboxes, shareable and forkable, with dependency pinning.',
   ],
   /* -------------------------------- planned -------------------------------- */
   [
      'ai-component-gen',
      'Q1 2027 — Prompt-to-component scaffolding',
      '✨',
      'planned',
      2,
      18,
      'CORE',
      'Q1 2027',
      null,
      ['1', '5'],
      '2026-08-02',
      'Generate a typed, themed component skeleton from a prompt, following the library conventions.',
   ],
   [
      'contrast-engine',
      'Q1 2027 — Automatic contrast resolution',
      '🎚️',
      'planned',
      2,
      19,
      'DESIGN',
      'Q1 2027',
      null,
      ['2', '4'],
      '2026-08-05',
      'Foreground tokens resolved from the actual background at runtime — AA guaranteed by construction.',
   ],
   [
      'wasm-layout',
      'Q1 2027 — WASM layout engine spike',
      '🧮',
      'planned',
      3,
      20,
      'PERF',
      'Q1 2027',
      null,
      ['6'],
      '2026-08-09',
      'Prototype the virtualized grid layout pass in WASM; go/no-go on a 10× row budget.',
   ],
   [
      'voice-input',
      'Q1 2027 — Voice input affordances',
      '🎤',
      'planned',
      4,
      21,
      'UX',
      'Q1 2027',
      null,
      ['16'],
      '2026-08-11',
   ],
   [
      'privacy-dashboard',
      'Q1 2027 — Public privacy dashboard',
      '🔒',
      'planned',
      3,
      0,
      'DATA',
      'Q1 2027',
      null,
      ['14'],
      '2026-08-14',
      'Live view of what telemetry exists, what it powers, and one switch to kill it all.',
   ],
   [
      'widget-kit',
      'Q1 2027 — Home-screen widget kit',
      '🧩',
      'planned',
      3,
      1,
      'MOBILE',
      'Q1 2027',
      null,
      ['20'],
      '2026-08-17',
   ],
   [
      'theming-marketplace',
      'Q2 2027 — Community theme gallery',
      '🖼️',
      'planned',
      4,
      2,
      'DESIGN',
      'Q2 2027',
      null,
      ['2', '9'],
      '2026-08-20',
      'Browse, preview and install community themes with one command.',
   ],
   [
      'offline-docs',
      'Q2 2027 — Offline-first docs app',
      '📴',
      'planned',
      4,
      3,
      'MOBILE',
      'Q2 2027',
      null,
      ['8'],
      '2026-08-22',
   ],
   [
      'perf-budget-api',
      'Q2 2027 — Per-app performance budgets',
      '⏱️',
      'planned',
      2,
      4,
      'PERF',
      'Q2 2027',
      null,
      ['6', '12'],
      '2026-08-25',
      'Apps declare budgets; the library warns in dev when a composition would bust them.',
   ],
   [
      'design-tokens-w3c',
      'Q2 2027 — W3C design tokens compliance',
      '📐',
      'planned',
      2,
      5,
      'DESIGN',
      'Q2 2027',
      null,
      ['2'],
      '2026-08-27',
      'Export and import the W3C tokens format losslessly, aliases included.',
   ],
   [
      'ecosystem-grants',
      'Q2 2027 — Ecosystem grants, second round',
      '🌾',
      'planned',
      3,
      6,
      null,
      'Q2 2027',
      null,
      ['11', '17'],
      '2026-08-29',
      'Fund ten community integrations; first round shipped four of five.',
   ],
   [
      'error-taxonomy',
      'Q1 2027 — One error taxonomy across the stack',
      '🏷️',
      'planned',
      2,
      7,
      'DATA',
      'Q1 2027',
      null,
      ['14'],
      '2026-08-30',
   ],
   /* ------------------------------- completed ------------------------------- */
   [
      'q2-tree-shaking',
      'Q2 — Tree-shakeable everything',
      '🌳',
      'completed',
      1,
      8,
      'PERF',
      'Q2 2026',
      'on-track',
      ['6', '12'],
      '2026-02-08',
      'Every entry point side-effect-free; importing one component costs one component.',
   ],
   [
      'q2-docs-playground',
      'Q2 — Live playground in every doc page',
      '🎪',
      'completed',
      2,
      9,
      'CORE',
      'Q2 2026',
      'on-track',
      ['5', '8'],
      '2026-02-20',
   ],
   [
      'q1-token-pipeline',
      'Q1 — Single-source token pipeline',
      '🔗',
      'completed',
      1,
      10,
      'DESIGN',
      'Q1 2026',
      'on-track',
      ['2'],
      '2025-12-15',
      'Tokens defined once, emitted to CSS, iOS, Android and Figma from the same source.',
   ],
   [
      'q1-support-rotation',
      'Q1 — Community support rotation',
      '🛟',
      'completed',
      3,
      11,
      null,
      'Q1 2026',
      'on-track',
      ['7'],
      '2025-12-20',
   ],
   [
      'q2-mobile-testbed',
      'Q2 — Real-device mobile testbed',
      '📵',
      'completed',
      2,
      12,
      'MOBILE',
      'Q2 2026',
      'on-track',
      ['20'],
      '2026-03-02',
      'A rack of mid-range devices running the visual suite on every release candidate.',
   ],
   /* -------------------------------- canceled ------------------------------- */
   [
      'css-in-js-runtime',
      'Runtime CSS-in-JS engine',
      '💅',
      'canceled',
      3,
      13,
      'PERF',
      'Q3 2026',
      null,
      ['6'],
      '2026-04-05',
      'Called off: zero-runtime extraction won the bake-off on every metric that mattered.',
   ],
   [
      'desktop-app-shell',
      'Desktop app shell (Electron kit)',
      '🖥️',
      'canceled',
      4,
      14,
      'CORE',
      'Q4 2026',
      null,
      ['13'],
      '2026-04-18',
      'Parked: demand concentrated on two customers, both fine with the web shell.',
   ],
   [
      'sponsor-tiers',
      'Sponsorware early-access tier',
      '💝',
      'canceled',
      4,
      15,
      null,
      'Q3 2026',
      null,
      ['17'],
      '2026-05-11',
      'Dropped after community feedback: early access split the ecosystem — features now ship for everyone.',
   ],
];

for (const [
   id,
   name,
   icon,
   seedStatus,
   priorityIdx,
   ownerIdx,
   leadTeamId,
   target,
   healthId,
   projectIds,
   createdAt,
   description,
] of seeds) {
   initiatives.push({
      id,
      name,
      description,
      icon,
      status: seedStatus,
      priority: priorities[priorityIdx],
      owner: ownerIdx === null ? undefined : users[ownerIdx],
      leadTeamId: leadTeamId ?? undefined,
      target,
      health: healthId ? byId(healthId) : noUpdate,
      projectIds,
      createdAt,
   });
}
