name: Generate Release Notes Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - develop
    paths:
      - VERSION  # Only trigger if the VERSION file changes

permissions:
  contents: write
  pull-requests: write

jobs:
  generate_notes:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate Release Notes
        run: |
          node ./scripts/release-notes.js

      - name: Comment Release Notes on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: RELEASE_NOTES.md
