name: Sync Features

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration file to use'
        required: false
        default: 'release.json'

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run sync-features script
        run: node ./scripts/sync-features.js --config ${{ inputs.config || 'release.json' }}

      - name: Run sync-labeler script
        run: node ./scripts/sync-labeler.js --config ${{ inputs.config || 'release.json' }}

      - name: Run commit-reference script
        run: node ./scripts/commit-reference.js --config ${{ inputs.config || 'release.json' }}

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: |
            chore: sync features, labels, and commit reference

            - Updated release.json with latest features
            - Synchronized .github/labeler.yml with feature labels
            - Generated commit reference documentation
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: chore/sync-features-${{ github.run_number }}
          base: ${{ github.ref_name }}
          delete-branch: true
          title: 'chore: sync features, labels, and commit reference'
          body: |
            ## 🔄 Automated Feature Sync

            This pull request was automatically generated by the sync-features workflow.

            ### Changes made:
            - ✅ Updated `release.json` with latest features from the codebase
            - ✅ Synchronized `.github/labeler.yml` with feature labels
            - ✅ Generated commit reference documentation at `/docs/commit-reference.md`

            ### Files affected:
            - `release.json`
            - `.github/labeler.yml`
            - `/docs/commit-reference.md`

            Please review the changes to ensure they are correct before merging.

            ---
            _Generated by sync-features workflow run #${{ github.run_number }}_
          labels: |
            chore
            automated
          add-paths: |
            release.json
            .github/labeler.yml
            docs/commit-reference.md


